# -*- coding: utf-8 -*-
"""data_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pFEhRQaQ_cujH_IKCQSKv_WprG6YXNNZ
"""

def load_image_with_bbox(path, label, x, y, w, h, pad=0.15):
    img_bytes = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img_bytes, channels=3)
    img = tf.cast(img, tf.float32)

    ih = tf.shape(img)[0]
    iw = tf.shape(img)[1]

    px = tf.cast(tf.round(w * pad), tf.int32)
    py = tf.cast(tf.round(h * pad), tf.int32)

    x1 = tf.cast(tf.round(x), tf.int32) - px
    y1 = tf.cast(tf.round(y), tf.int32) - py
    x2 = tf.cast(tf.round(x + w), tf.int32) + px
    y2 = tf.cast(tf.round(y + h), tf.int32) + py

    x1 = tf.clip_by_value(x1, 0, iw - 1)
    y1 = tf.clip_by_value(y1, 0, ih - 1)
    x2 = tf.clip_by_value(x2, 1, iw)
    y2 = tf.clip_by_value(y2, 1, ih)

    cropped = img[y1:y2, x1:x2, :]
    cropped = tf.image.resize(cropped, (IMG_SIZE, IMG_SIZE))
    return cropped, label

def train_map_bbox(path, label, x, y, w, h):
    img, label = load_image_with_bbox(path, label, x, y, w, h)
    img = augmenter(img, training=True)
    img = preprocess(img)
    return img, label

def eval_map_bbox(path, label, x, y, w, h):
    img, label = load_image_with_bbox(path, label, x, y, w, h)
    img = preprocess(img)
    return img, label

def make_ds_bbox(frame, training: bool):
    paths = frame["filepath"].values
    labels = (frame["class_id"].values - 1).astype(np.int32)
    xs = frame["x"].values.astype(np.float32)
    ys = frame["y"].values.astype(np.float32)
    ws = frame["w"].values.astype(np.float32)
    hs = frame["h"].values.astype(np.float32)

    ds = tf.data.Dataset.from_tensor_slices((paths, labels, xs, ys, ws, hs))
    if training:
        ds = ds.shuffle(buffer_size=len(frame), seed=SEED, reshuffle_each_iteration=True)
        ds = ds.map(train_map_bbox, num_parallel_calls=AUTOTUNE)
    else:
        ds = ds.map(eval_map_bbox, num_parallel_calls=AUTOTUNE)

    return ds.batch(BATCH_SIZE).prefetch(AUTOTUNE)

train_ds = make_ds_bbox(train_df2, training=True)
val_ds   = make_ds_bbox(val_df, training=False)
test_ds  = make_ds_bbox(test_df, training=False)