# -*- coding: utf-8 -*-
"""model1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1freQNrakkjG2MEEy97h-HXHNKuukQBXR

# Model 1: EfficientNet-B2 Model with fine tuning
"""

# Build EfficientNet-B2 Model and Train Classification Head (Transfer Learning)

import tensorflow as tf
import os

base = tf.keras.applications.EfficientNetB2(
    include_top=False,
    weights="imagenet",
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)
base.trainable = False

inputs = tf.keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = base(inputs, training=False)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.Dropout(0.30)(x)
outputs = tf.keras.layers.Dense(NUM_CLASSES, activation="softmax", dtype="float32")(x)

model = tf.keras.Model(inputs, outputs, name="standard_efficientnetb2")

# CategoricalCrossentropy
model.compile(
    optimizer=tf.keras.optimizers.AdamW(learning_rate=1e-3, weight_decay=1e-4),
    loss=tf.keras.losses.CategoricalCrossentropy(),
    metrics=["accuracy"]
)

os.makedirs("/content/checkpoints", exist_ok=True)
ckpt_path = "/content/checkpoints/standard_efficientnetb2_best.keras"

callbacks = [
    tf.keras.callbacks.ModelCheckpoint(ckpt_path, monitor="val_accuracy", mode="max",
                                       save_best_only=True, verbose=1),
    tf.keras.callbacks.EarlyStopping(monitor="val_accuracy", mode="max",
                                     patience=3, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5,
                                         patience=2, min_lr=1e-6, verbose=1),
]

history = model.fit(train_ds_mix, validation_data=val_ds_oh, epochs=12, callbacks=callbacks)
print("Saved best head-trained model at:", ckpt_path)

# Fine-tuning with Cosine Decay LR

model = tf.keras.models.load_model("/content/checkpoints/standard_efficientnetb2_best.keras", compile=False)

# Unfreeze only last N layers and keep BatchNorm frozen
N = 40
for layer in model.layers:
    if isinstance(layer, tf.keras.Model) and "efficientnet" in layer.name.lower():
        for sublayer in layer.layers[:-N]:
            sublayer.trainable = False
        for sublayer in layer.layers[-N:]:
            if isinstance(sublayer, tf.keras.layers.BatchNormalization):
                sublayer.trainable = False
            else:
                sublayer.trainable = True

# Cosine decay schedule
steps_per_epoch = int(np.ceil(len(train_df2) / BATCH_SIZE))
fine_tune_epochs = 10
total_steps = steps_per_epoch * fine_tune_epochs

ft_lr = tf.keras.optimizers.schedules.CosineDecay(
    initial_learning_rate=5e-6,
    decay_steps=total_steps,
    alpha=0.1
)

model.compile(
    optimizer=tf.keras.optimizers.AdamW(learning_rate=ft_lr, weight_decay=1e-4),
    loss=tf.keras.losses.CategoricalCrossentropy(),
    metrics=["accuracy"]
)

ft_ckpt = "/content/checkpoints/standard_efficientnetb2_finetuned_best_bbox.keras"

callbacks = [
    tf.keras.callbacks.ModelCheckpoint(ft_ckpt, monitor="val_accuracy", mode="max",
                                       save_best_only=True, verbose=1),
    tf.keras.callbacks.EarlyStopping(monitor="val_accuracy", mode="max",
                                     patience=3, restore_best_weights=True),
]

history_ft = model.fit(train_ds_mix, validation_data=val_ds_oh, epochs=fine_tune_epochs, callbacks=callbacks)
print("Saved best fine-tuned model at:", ft_ckpt)