# -*- coding: utf-8 -*-
"""model2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13hkf_XOp5OaXiEg4xAjySujXw8F96W49

# Model 2: ImageNet backbone and custom head
"""

import os
import numpy as np
import tensorflow as tf
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix

# One-hot labels and CutMix/MixUp

def onehot_map(x, y):
    y = tf.one_hot(tf.cast(y, tf.int32), NUM_CLASSES)
    return x, y

# Convert base datasets to one-hot labels
train_ds_oh = train_ds.map(onehot_map, num_parallel_calls=AUTOTUNE)
val_ds_oh   = val_ds.map(onehot_map,   num_parallel_calls=AUTOTUNE).cache()
test_ds_oh  = test_ds.map(onehot_map,  num_parallel_calls=AUTOTUNE).cache()

# Augment probs and strengths
MIXUP_ALPHA  = 0.2
CUTMIX_ALPHA = 1.0
P_MIXUP  = 0.5
P_CUTMIX = 0.5

def sample_beta(size, alpha):
    gamma1 = tf.random.gamma([size], alpha, dtype=tf.float32)
    gamma2 = tf.random.gamma([size], alpha, dtype=tf.float32)
    return gamma1 / (gamma1 + gamma2)

def mixup_batch(x, y, alpha=MIXUP_ALPHA):
    B = tf.shape(x)[0]
    lam = sample_beta(B, alpha)
    lam_x = tf.cast(tf.reshape(lam, [B, 1, 1, 1]), x.dtype)
    lam_y = tf.cast(tf.reshape(lam, [B, 1]), y.dtype)

    idx = tf.random.shuffle(tf.range(B))
    x2 = tf.gather(x, idx)
    y2 = tf.gather(y, idx)

    x_out = x * lam_x + x2 * (tf.cast(1.0, x.dtype) - lam_x)
    y_out = y * lam_y + y2 * (tf.cast(1.0, y.dtype) - lam_y)
    return x_out, y_out

def cutmix_batch(x, y, alpha=CUTMIX_ALPHA):
    B = tf.shape(x)[0]
    H = tf.shape(x)[1]
    W = tf.shape(x)[2]

    idx = tf.random.shuffle(tf.range(B))
    x2 = tf.gather(x, idx)
    y2 = tf.gather(y, idx)

    lam = sample_beta(B, alpha)
    cut_rat = tf.sqrt(1.0 - lam)

    cut_w = tf.cast(tf.cast(W, tf.float32) * cut_rat, tf.int32)
    cut_h = tf.cast(tf.cast(H, tf.float32) * cut_rat, tf.int32)

    cx = tf.random.uniform([B], 0, W, dtype=tf.int32)
    cy = tf.random.uniform([B], 0, H, dtype=tf.int32)

    x1 = tf.clip_by_value(cx - cut_w // 2, 0, W)
    y1 = tf.clip_by_value(cy - cut_h // 2, 0, H)
    x2b = tf.clip_by_value(cx + cut_w // 2, 0, W)
    y2b = tf.clip_by_value(cy + cut_h // 2, 0, H)

    # mask [B,H,W,1]
    xs = tf.reshape(tf.range(W), [1, 1, W, 1])
    ys = tf.reshape(tf.range(H), [1, H, 1, 1])

    x1_ = tf.reshape(x1,  [B, 1, 1, 1])
    x2_ = tf.reshape(x2b, [B, 1, 1, 1])
    y1_ = tf.reshape(y1,  [B, 1, 1, 1])
    y2_ = tf.reshape(y2b, [B, 1, 1, 1])

    mask = tf.logical_and(tf.logical_and(xs >= x1_, xs < x2_),
                          tf.logical_and(ys >= y1_, ys < y2_))
    mask = tf.cast(mask, x.dtype)

    x_out = x * (tf.cast(1.0, x.dtype) - mask) + x2 * mask

    # adjust lambda by actual area
    area = tf.cast((x2b - x1) * (y2b - y1), tf.float32)
    total = tf.cast(H, tf.float32) * tf.cast(W, tf.float32)
    lam_adj = 1.0 - (area / (total + 1e-9))
    lam_adj_y = tf.cast(tf.reshape(lam_adj, [B, 1]), y.dtype)

    y_out = y * lam_adj_y + y2 * (tf.cast(1.0, y.dtype) - lam_adj_y)
    return x_out, y_out

def mix_augment(x, y):
    r = tf.random.uniform([], 0, 1)

    def do_mixup():
        return mixup_batch(x, y, MIXUP_ALPHA)

    def do_cutmix():
        return cutmix_batch(x, y, CUTMIX_ALPHA)

    def do_none():
        return x, y

    return tf.cond(
        r < P_MIXUP,
        do_mixup,
        lambda: tf.cond(r < (P_MIXUP + P_CUTMIX), do_cutmix, do_none)
    )

train_ds_mix2 = train_ds_oh.map(mix_augment, num_parallel_calls=AUTOTUNE)

# Smoke test
for xb, yb in train_ds_mix2.take(1):
    print("Model2 aug batch:", xb.shape, xb.dtype, "| labels:", yb.shape, yb.dtype,
          "| label sum ~1:", float(tf.reduce_mean(tf.reduce_sum(yb, axis=1))))

# Build Model 2: ImageNet backbone and custom head

def build_model2(input_shape=(IMG_SIZE, IMG_SIZE, 3), num_classes=NUM_CLASSES, dropout=0.35):
    inputs = tf.keras.Input(shape=input_shape)

    backbone = tf.keras.applications.EfficientNetB0(
        include_top=False,
        weights="imagenet",
        input_shape=input_shape
    )
    backbone.trainable = False

    x = backbone(inputs, training=False)

    # Custom channel-attention gate
    s = tf.keras.layers.GlobalAveragePooling2D()(x)
    s = tf.keras.layers.Dense(256, activation="swish")(s)
    s = tf.keras.layers.Dense(x.shape[-1], activation="sigmoid")(s)
    s = tf.keras.layers.Reshape((1, 1, x.shape[-1]))(s)
    x = tf.keras.layers.Multiply()([x, s])

    # Pooling and custom MLP head
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(dropout)(x)
    x = tf.keras.layers.Dense(512, activation="swish")(x)
    x = tf.keras.layers.Dropout(dropout)(x)

    outputs = tf.keras.layers.Dense(num_classes, activation="softmax", dtype="float32")(x)
    model = tf.keras.Model(inputs, outputs, name="model2_custom_birdnet")
    return model

model2 = build_model2()
model2.summary()

# Head training

os.makedirs("/content/checkpoints", exist_ok=True)
m2_ckpt = "/content/checkpoints/model2_custom_best.keras"

model2.compile(
    optimizer=tf.keras.optimizers.AdamW(learning_rate=3e-4, weight_decay=1e-4),
    loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.05),
    metrics=["accuracy"]
)

callbacks = [
    tf.keras.callbacks.ModelCheckpoint(m2_ckpt, monitor="val_accuracy", mode="max",
                                       save_best_only=True, verbose=1),
    tf.keras.callbacks.EarlyStopping(monitor="val_accuracy", mode="max",
                                     patience=6, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5,
                                         patience=2, min_lr=1e-6, verbose=1),
]

history_m2 = model2.fit(
    train_ds_mix2,
    validation_data=val_ds_oh,
    epochs=40,
    callbacks=callbacks
)

print("Saved best Model 2 head-trained checkpoint at:", m2_ckpt)

# Fine-tuning + Cosine decay

model2 = tf.keras.models.load_model(m2_ckpt, compile=False)

N = 60
for layer in model2.layers:
    if isinstance(layer, tf.keras.Model) and "efficientnet" in layer.name.lower():
        for sublayer in layer.layers[:-N]:
            sublayer.trainable = False
        for sublayer in layer.layers[-N:]:
            if isinstance(sublayer, tf.keras.layers.BatchNormalization):
                sublayer.trainable = False
            else:
                sublayer.trainable = True

steps_per_epoch = int(np.ceil(len(train_df2) / BATCH_SIZE))
fine_tune_epochs = 15
total_steps = steps_per_epoch * fine_tune_epochs

ft_lr = tf.keras.optimizers.schedules.CosineDecay(
    initial_learning_rate=8e-6,
    decay_steps=total_steps,
    alpha=0.1
)

m2_ft_ckpt = "/content/checkpoints/model2_custom_finetuned_best.keras"

model2.compile(
    optimizer=tf.keras.optimizers.AdamW(learning_rate=ft_lr, weight_decay=1e-4),
    loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.02),
    metrics=["accuracy"]
)

callbacks_ft = [
    tf.keras.callbacks.ModelCheckpoint(m2_ft_ckpt, monitor="val_accuracy", mode="max",
                                       save_best_only=True, verbose=1),
    tf.keras.callbacks.EarlyStopping(monitor="val_accuracy", mode="max",
                                     patience=5, restore_best_weights=True),
]

history_m2_ft = model2.fit(
    train_ds_mix2,
    validation_data=val_ds_oh,
    epochs=fine_tune_epochs,
    callbacks=callbacks_ft
)

print("Saved best Model 2 fine-tuned checkpoint at:", m2_ft_ckpt)